### ISSUE TITLE
Change exposed Swool Port to 80 instead of 8080

### ISSUE THREAD

**Issue by bjesuiter** [shlinkio/shlink-docker-image#44]
In your Dockerfile, Swool gets startet on port 8080. 

I want to use your container in a docker-compose setup in combination with 
[nginx-reverse-proxy](https://github.com/evertramos/docker-compose-letsencrypt-nginx-proxy-companion) setup from evertramos.   
Unfortunately, this reverse proxy needs the container to publish its service on port 80 and i can't change that. 

So my question is: Could you please change the port of your docker container to 80? 
If people want to expose a different port on the host machine, they can use regular port mapping, like "8080:80" in docker-compose. 

The problem is, that the "expose" keyword in docker-compose allows me to expose one port of a container, but it does not allow me to do a mapping of your internal port 8080 to my required port 80. 

If you don't want to change the port, I must recreate your docker-image, which would be more work than I would like to do. 
However, if you have a better idea on how to make the port customizable from the outside, i'm very interested. 

Please ask, when you have questions! :)

**Comment by acelaya** [comment]
According to this nginx proxy image docs, you can define the port of the proxied service using the `VIRTUAL_PORT` env var.

It would be a quite bad reverse proxy if it was forcing you to use port 80 :sweat_smile:

**Comment by bjesuiter** [comment]
Ahhh, I somehow overlooked that! :| Thank you for pointing that out! I'll
test this tomorrow!

Alejandro Celaya <notifications@github.com> schrieb am Sa., 20. Apr. 2019,
23:02:
